source 'http://rubygems.org'
group :development do
  gem 'rb-fsevent', :require => false
  gem 'guard'
  gem 'growl'
  gem 'terminal-notifier-guard'
  gem 'guard-shell'
  gem 'guard-rsync'
  # gem 'guard-jenkins'
end
