# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#

guard :shell do
  watch(%r{^(?:src)/.+\.(scala|java)$}) {
    |m| `/scala/trunk/tools/jarsync.sh #{m[0]}`
  }
end
