#!/bin/sh
#

thisdir=$(dirname $BASH_SOURCE)
abs=$thisdir/abspath
lib=$($abs $thisdir/../lib)
build=$($abs $thisdir/../build)

cp=$(${thisdir}/cpof ${build}/locker/classes):${build}/asm/classes 

echo ${cp}:$LIBDIR/fjbg.jar:$LIBDIR/msil.jar:$LIBDIR/forkjoin.jar:$LIBDIR/jline.jar:$LIBDIR/extra/'*'
