#!/bin/sh
#

THISDIR=$(dirname $BASH_SOURCE)
ABS=${THISDIR}/abspath
LIBDIR=$($ABS $THISDIR/../lib)

cp=$(${THISDIR}/cpof ${THISDIR}/../build/locker/classes)

echo ${cp}:$LIBDIR/fjbg.jar:$LIBDIR/msil.jar:$LIBDIR/forkjoin.jar:$LIBDIR/jline.jar:$LIBDIR/asm.jar:$LIBDIR/extra/'*'
